/*
 The MySensors library adds a new layer on top of the RF24 library.
 It handles radio network routing, relaying and ids.

 Created by Henrik Ekblad <henrik.ekblad@gmail.com>
	
 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 version 2 as published by the Free Software Foundation.
*/

#ifndef MySensor_h
#define MySensor_h

#include "Version.h"   // Auto generated by bot
#include "MyConfig.h"
#include "MyMessage.h"
#include <nRF24L01.h>
#include <RF24.h>
#include <RF24_config.h>
#include <Arduino.h>
#include <stddef.h>
#include <SPI.h>
#include <avr/eeprom.h>
#include <avr/pgmspace.h>
#include <stdarg.h>

#ifdef DEBUG
#define debug(x,...) debugPrint(x, ##__VA_ARGS__)
#else
#define debug(x,...)
#endif

#define BAUD_RATE 115200

#define AUTO 0xFF // 0-254. Id 255 is reserved for auto initialization of nodeId.
#define NODE_CHILD_ID 0xFF // Node child id is always created for when a new sensor is detected

#define EEPROM_START 0
#define EEPROM_NODE_ID_ADDRESS EEPROM_START // Where to store radio id in EEPROM
#define EEPROM_PARENT_NODE_ID_ADDRESS (EEPROM_START+1) // Where to store relay id in EEPROM
#define EEPROM_DISTANCE_ADDRESS (EEPROM_PARENT_NODE_ID_ADDRESS+1) // Where to store distance to gateway in EEPROM
#define EEPROM_ROUTES_ADDRESS (EEPROM_DISTANCE_ADDRESS+1) // Where to start storing routing information in EEPROM. Will allocate 256 bytes.


// This is the nodeId for sensor net gateway receiver sketch (where all sensors should send their data).
// This is also act as base value for sensor nodeId
#define BASE_RADIO_ID ((uint64_t)0xA8A8E1FC00LL)
#define GATEWAY_ADDRESS ((uint8_t)0)
#define BROADCAST_ADDRESS ((uint8_t)0xFF)
#define TO_ADDR(x) (BASE_RADIO_ID + x)

#define WRITE_PIPE ((uint8_t)0)
#define CURRENT_NODE_PIPE ((uint8_t)1)
#define BROADCAST_PIPE ((uint8_t)2)

#define SEND_RETRIES 3
#define FIND_RELAY_AFTER_FAILED_TRANSMISSIONS 5

#define build(_msg, _sender, _destination, _sensor, _cmd, _type) \
	_msg.sender = _sender; \
	_msg.destination = _destination;\
	_msg.sensor = _sensor; \
	_msg.type = _type; \
	mSetCommand(_msg,_cmd); \

#define buildSend(_msg, _sender, _destination, _sensor, _cmd, _type) \
	build(_msg, _sender, _destination, _sensor, _cmd, _type) \
	sendRoute(_msg);

#define buildSendPayload(_msg, _sender, _destination, _sensor, _cmd, _type, _value) \
	build(_msg, _sender, _destination, _sensor, _cmd, _type) \
	_msg.set(_value); \
	sendRoute(_msg);


class MySensor : public RF24
{
  public:
	/**
	* Constructor
	*
	* Creates a new instance of Sensor class.
	*
	* @param _cepin The pin attached to RF24 Chip Enable on the RF module (defualt 9)
	* @param _cspin The pin attached to RF24 Chip Select (default 10)
	*/
	MySensor(uint8_t _cepin=9, uint8_t _cspin=10);

	/**
	* Begin operation of the MySensors library
	*
	* Call this in setup(), before calling any other sensor net library methods.
	* @param incomingMessageCallback Callback function for incoming messages. Default is NULL
	* @param relayMode Activate relay mode. This node will forward messages to other nodes in the radio network. Make sure to call process() regularly. Default in false
	* @param nodeId The unique id (1-254) for this sensor. Default is AUTO(255) which means sensor tries to fetch an id from controller.
	* @param paLevel Radio PA Level for this sensor. Default RF24_PA_MAX
	* @param channel Radio channel. Default is channel 76
	* @param dataRate Radio transmission speed. Default RF24_1MBPS
	*/

	void begin(void (* msgCallback)(MyMessage)=NULL, boolean relayMode=false, uint8_t nodeId=AUTO, rf24_pa_dbm_e paLevel=RF24_PA_LEVEL, uint8_t channel=RF24_CHANNEL, rf24_datarate_e dataRate=RF24_DATARATE);

	/**
	 * Return the nodes nodeId.
	 */
	uint8_t getNodeId();

	/**
	* Each node must present all attached sensors before any values can be handled correctly by the controller.
    * It is usually good to present all attached sensors after power-up in setup().
	*
	* @param sensorId Select a unique sensor id for this sensor. Choose a number between 0-254.
	* @param sensorType The sensor type. See sensor typedef in Message.h.
	*/
	void present(uint8_t sensorId, uint8_t sensorType);

	/**
	 * Sends sketch meta information to the gateway. Not mandatory but a nice thing to do.
	 * @param name String containing a short Sketch name or NULL  if not applicable
	 * @param version String containing a short Sketch version or NULL if not applicable
	 */
	void sketchInfo(const char *name, const char *version);

	/**
	* Sends a message to gateway or one of the other nodes in the radio network
	*
	* @param msg Message to send
	* @param ack Set this to true if you want destination node to send ack back to this node. Default is not to request any ack.
	* @param retry Number of attempts before giving up. Default is SEND_RETRIES
	* @return true Retuns false if ack is enabled and no ack came back
	*/
	bool send(MyMessage msg, bool ack=false/*, uint8_t retry=SEND_RETRIES*/);

	/**
	 * Send this nodes battery level to gateway.
	 * @param level Level between 0-100(%)
	 */
	void sendBatteryLevel(uint8_t level);

	/**
	* Fetches a value from gateway or some other sensor in the radio network. Resends request and waits for response.
	* Note that if you have registered a callback in begin() it will also be called before message is returned
	* by get()
	*
	* @param childSensorId  The unique child id for the different sensors connected to this arduino. 0-254.
	* @param variableType The variableType to fetch
	* @param destination The nodeId of other node in radio network. Default is gateway
	* @param number of attempts to fetch
	* @return Message response
	*/
//	MyMessage get(uint8_t childSensorId, uint8_t variableType, uint8_t destination=GATEWAY_ADDRESS, uint8_t retry=SEND_RETRIES);

	/**
	* Requests a value from gateway or some other sensor in the radio network.
	* Make sure to add callback in begin() to handle request response.
	*
	* @param childSensorId  The unique child id for the different sensors connected to this arduino. 0-254.
	* @param variableType The variableType to fetch
	* @param callback for result. This will be called when a message reply is received or request fails (see status of second argument).
	* @param destination The nodeId of other node in radio network. Default is gateway
	*/
	void request(uint8_t childSensorId, uint8_t variableType, uint8_t destination=GATEWAY_ADDRESS);


	/**
	 * Requests time from controller. Pick up response in callback.
	 *
	 * @return Seconds since 1970.
	 */
	void requestTime();

	/**
	 * Fetches configuration from controller. Returns true if metric system has been selected which means
	 * that sensor should report it's information in:
	 * celsius, meter, cm, gram, km/h, m/s etc..
	 * If false is returned the sensor should report data in imperial system which means
	 * fahrenheit, feet, gallon, mph etc...
	 */
	void requestConfiguration();


	/**
	 * Processes incoming messages to this node. If this is a relaying node it will
	* Returns true if there is a message addressed for this node just was received.
	* Use callback to handle incoming messages.
	*/
	boolean process(void);

	/**
	* Returns the last received message
	*/
	MyMessage getLastMessage(void);



#ifdef DEBUG
	void debugPrint(const char *fmt, ... );
	int freeRam();
#endif

  protected:
	struct settings_t
	{
		uint8_t nodeId; // Current node id
		uint8_t parentNodeId; // Where this node sends its messages
		uint8_t distance; // This nodes distance to sensor net gateway (number of hops)
		uint8_t *childNodeTable; // In memory buffer for routing to other nodes. also stored in EEPROM
	} s;
	MyMessage msg;  // Buffer for incoming messages.
	uint8_t failedTransmissions;
	boolean relayMode;

	void setupRelayMode();
	void setupRadio(rf24_pa_dbm_e paLevel, uint8_t channel, rf24_datarate_e dataRate);
	void findParentNode();
	boolean sendRoute(MyMessage message);
	boolean sendWrite(uint8_t dest, MyMessage message, bool broadcast=false);
	uint8_t validate(MyMessage message);

  private:
	MyMessage ack;  // Buffer for ack messages.
    void (*msgCallback)(MyMessage); // Callback for undefined incoming messages

	void requestNodeId();
	uint8_t crc8Message(MyMessage);

	uint8_t getChildRoute(uint8_t childId);
	void addChildRoute(uint8_t childId, uint8_t route);
	void removeChildRoute(uint8_t childId);
};

#endif
